# Generated by Django 2.1.4 on 2019-03-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DecryptApp', '0002_auto_20190130_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DecryptApp.UploadFile')),
            ],
        ),
    ]
